### ISSUE TITLE
Calculate scheduled headway per event

### ISSUE THREAD

**Issue by mathcolo** [transitmatters/gobble#3]
In order to display colored dots in the data dashboard, `scheduled_headway` [needs to be filled in](https://github.com/transitmatters/gobble/blob/9d9fc8e0a7ad6dc0569422df3b2198f1165ea31f/src/gobble.ts#L101).

Unfortunately, we don't immediately know what the scheduled headway is from a particular vehicle, so we need to calculate it ourselves from GTFS. It also might be possible to request them on-demand, once per day, from the MBTA v3 API.

**Comment by hamima-halim** [comment]
What's the preferred way to define the `scheduled_headway` for the first stop in a route for a given day? There's about 4 hours of dead time. We could grab yesterday's `stop_times.txt` if we have the previous `trip_id` for that route, but I'd also buy if this is somewhat of a nonsensical notion and we are happy to slap a NaN on that bad boy

**Comment by hamima-halim** [comment]
This was fixed in https://github.com/transitmatters/gobble/pull/7!
